#!/bin/bash

echo "Enter the number of values you want to sum:"
read n

sum=0

for ((i=1; i<=n; i++))
do
    echo "Enter value $i:"
    read value
    sum=$((sum+value))
done

average=$(echo "scale=2; $sum/$n" | bc)

echo "Sum: $sum"
echo "Average: $average"
